version: "2"
run:
  timeout: 5m
linters:
  enable:
    - bodyclose
    - dupl
    - gocritic
    - gocyclo
    - revive
    - godot
    - mnd
    - prealloc
    - unparam
formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: package-comments
        disabled: true
  mnd:
    ignored-numbers: ['0', '1', '2', '3']
issues:
  exclude-use-default: false
  exclude-dirs-use-default: true
